#!/usr/bin/env python
#
# Convert bases using alphabet method.
#
# Beware leading zeros - they won't convert as you expect.
# Mathematically, the first alphabet digit is zero.
#

import sys

def b2b(nin, ain, aout):
	out = ''
	num = 0L
	for i,c in enumerate(nin[::-1]):
		num += ain.index(c)*len(ain)**i
	while num >= len(aout):
		num,m = divmod(num, len(aout))
		out = aout[m] + out
	return aout[num] + out
	
if len(sys.argv) < 3:
	print "Usage: %s <input number> <input alphabet> <output alphabet>\n" % sys.argv[0]
	sys.exit(1)

print b2b(sys.argv[1], sys.argv[2], sys.argv[3])
