#!/usr/bin/python

# need zbar and clipboard python modules, try pip install

from sys import argv
import zbar, clipboard

# create a Processor
proc = zbar.Processor()

# configure the Processor
proc.parse_config('enable')

# initialize the Processor
device = '/dev/video0'
if len(argv) > 2:
    device = argv[2]
proc.init(device)

# enable the preview window
proc.visible = True

# read at least one barcode (or until window closed)
proc.process_one()

# hide the preview window
proc.visible = False

# extract results
for symbol in proc.results:
	clipboard.copy(symbol.data if argv[1] != 'strip' else symbol.data.split(':')[-1])
    
