#!/usr/bin/env python

import hmac, base64, hashlib, urllib2, json

base = 'https://data.mtgox.com/api/2/'
secret = ''
key = ''

def gox(path, data=None):

    if not data:
        return urllib2.urlopen(base + path).read()
        
    hash_data = path + chr(0) + data
    secret = base64.b64decode(secret)
    sha512 = hashlib.sha512
    hmac = str(hmac.new(secret, hash_data, sha512))

    header = {
        'User-Agent': 'My-First-Trade-Bot',
        'Rest-Key': key,
        'Rest-Sign': base64.b64encode(hmac),
        #'Accept-encoding': 'GZIP',
    }

    return urllib2.urlopen(urllib2.Request(base + path, data, header), data).read()
    
print json.dumps(json.loads(gox('BTCUSD/money/ticker')), indent=4, separators=(',', ': '))

print json.dumps(json.loads(gox('BTCUSD/money/order/lag')), indent=4, separators=(',', ': '))

