#!/usr/bin/env python
#
# Add Hex or 12 word Electrum seeds to create a "combined" seed.
#
# Usage: addseeds 
#
# Reads [32 Hex chars] or [12 words] per line
#
# Outputs sum of seeds as 12 words
#

import sys, mnemonic

if __name__ == '__main__':
    
    seedsum = 0
    for seed in sys.stdin:
        seed = seed.strip()
        if len(seed) == 32:
            print ' '.join(mnemonic.mn_encode(seed))
            seedsum += long(seed, 16)
        else:
            print seed
            seedsum += long(mnemonic.mn_decode(seed.split()), 16)

    print ' '.join(mnemonic.mn_encode('%0.32x' %seedsum)) 
